version: '3.8'

services:
  autofilter-bot:
    build: .
    container_name: autofilter-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: autofilter-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - bot-network
    ports:
      - "6379:6379"

volumes:
  redis_data:

networks:
  bot-network:
    driver: bridge